apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: http://charts.gitlab.io/
    targetRevision: 9.2.1
    chart: gitlab
    helm:
      valuesFiles:
        - $values/apps/gitlab/Values.yaml
  - repoURL: https://github.com/Steven4Hooisma/Xmpl.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true