apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.0.13
    chart: ingress-nginx
    helm:
      valuesFiles:
        - $values/apps/nginx-ingress/Values.yaml
  - repoURL: https://github.com/Steven4Hooisma/Xmpl.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true